name: pytest

on: [push]

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Run pytest
      uses: fylein/python-pytest-github-action@v1
      with:
        args: pip3 install -r requirements.txt && pytest test/unit
